package com.bcbs239.regtech.reportgeneration.domain.shared.valueobjects;

/**
 * Type of generated report
 * Represents the different report formats that can be generated
 */
public enum ReportType {
    /**
     * Comprehensive report combining Large Exposures and Data Quality analysis
     * This is the primary report type generated by the system
     */
    COMPREHENSIVE,
    
    /**
     * Large Exposures only report (Grandi Esposizioni)
     * Contains only risk calculation and exposure analysis
     */
    LARGE_EXPOSURES,
    
    /**
     * Data Quality only report
     * Contains only data quality validation results and recommendations
     */
    DATA_QUALITY
}
