# IAM Module Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/regtech
    username: regtech_user
    password: ${DATABASE_PASSWORD:regtech_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: iam
        format_sql: true
        show_sql: false
    show-sql: false
  
  flyway:
    locations: classpath:db/migration
    schemas: iam
    baseline-on-migrate: true
    validate-on-migrate: true

# IAM specific configuration
iam:
  security:
    jwt:
      secret: ${JWT_SECRET:your-jwt-secret-key-here}
      expiration: 86400 # 24 hours in seconds
    password:
      min-length: 12
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID:}
        client-secret: ${GOOGLE_CLIENT_SECRET:}
      facebook:
        client-id: ${FACEBOOK_CLIENT_ID:}
        client-secret: ${FACEBOOK_CLIENT_SECRET:}
  
  authorization:
    cache:
      enabled: true
      ttl: 300 # 5 minutes
    multi-tenant:
      enabled: true
      default-organization: "default-org"
    permissions:
      strict-mode: true
      audit-enabled: true

# Logging configuration
logging:
  level:
    com.bcbs239.regtech.iam: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Development profile
spring:
  config:
    activate:
      on-profile: development
  
  datasource:
    url: jdbc:h2:mem:regtech-iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: PUBLIC
  
  flyway:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:regtech-iam-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: PUBLIC
  
  flyway:
    enabled: false