# IAM Module Production Profile Configuration
spring:
  datasource:
    # PostgreSQL database for production
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:regtech}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:regtech_user}
    password: ${DB_PASSWORD}
    
    # Connection pool configuration for production
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: IamHikariCP
      
  jpa:
    hibernate:
      ddl-auto: validate # Never auto-create/update schema in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: iam
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: iam
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true # Prevent accidental data loss

iam:
  security:
    jwt:
      # Production JWT secret (must be provided via environment variables)
      secret: ${JWT_SECRET}
      expiration: 3600 # 1 hour for production (shorter for security)
    password:
      # Strong password policy for production
      min-length: 12
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
      facebook:
        client-id: ${FACEBOOK_CLIENT_ID}
        client-secret: ${FACEBOOK_CLIENT_SECRET}
  
  authorization:
    cache:
      enabled: true
      ttl: 300 # 5 minutes
    multi-tenant:
      enabled: true
      default-organization: ${DEFAULT_ORGANIZATION:default-org}
    permissions:
      strict-mode: true
      audit-enabled: true

# Production logging configuration
logging:
  level:
    com.bcbs239.regtech.iam: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.transaction: WARN
    org.springframework.web: WARN
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    
  file:
    name: /var/log/regtech/iam.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

# Production actuator endpoints (restricted)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  security:
    enabled: true
    
# Production security configuration
server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    
# Production-specific environment validation
iam-validation:
  required-env-vars:
    - JWT_SECRET
    - DB_PASSWORD
    - DB_HOST
    - DB_NAME
    - DB_USERNAME