# IAM Module Default Configuration
iam:
  security:
    jwt:
      secret: ${JWT_SECRET:your-jwt-secret-key-here}
      expiration: 86400 # 24 hours in seconds
    password:
      min-length: 12
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID:}
        client-secret: ${GOOGLE_CLIENT_SECRET:}
      facebook:
        client-id: ${FACEBOOK_CLIENT_ID:}
        client-secret: ${FACEBOOK_CLIENT_SECRET:}
  
  authorization:
    cache:
      enabled: true
      ttl: 300 # 5 minutes
    multi-tenant:
      enabled: true
      default-organization: "default-org"
    permissions:
      strict-mode: true
      audit-enabled: true

# Logging configuration
logging:
  level:
    com.bcbs239.regtech.iam: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN