# Billing Module Configuration
billing:
  stripe:
    # Stripe API configuration (will be overridden by environment variables)
    api-key: ${STRIPE_API_KEY:sk_test_placeholder}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_placeholder}
    
  # Subscription tier configuration
  tiers:
    starter:
      monthly-price: 500.00
      currency: EUR
      exposure-limit: 10000
      
  # Dunning process configuration
  dunning:
    reminder-intervals:
      step-1: 7  # days after due date
      step-2: 14 # days after step 1
      step-3: 21 # days after step 2
    final-action-delay: 30 # days after step 3
    
  # Invoice configuration
  invoices:
    due-days: 14 # days from issue date
    currency: EUR
    
  # Billing cycle configuration
  billing-cycle:
    timezone: Europe/Amsterdam
    billing-day: 1 # first day of month
    
  # Outbox pattern configuration
  outbox:
    enabled: true
    processing-interval: 30000 # milliseconds
    retry-interval: 120000 # milliseconds
    max-retries: 3
    cleanup-interval: 86400000 # 24 hours in milliseconds
    cleanup-retention-days: 7
    
# Logging configuration for billing module
logging:
  level:
    com.bcbs239.regtech.billing: INFO
    com.stripe: WARN