package com.bcbs239.regtech.core.application;

import java.util.UUID;

import lombok.Getter;

/**
 * Base class for application commands.
 *
 * Provides a generated unique identifier for each command instance. Commands
 * that are implemented as regular classes can extend this base to inherit an
 * auto-generated id. Records cannot extend classes, so they should include a
 * commandId field (generated by their factory) if they need the id.
 */
@Getter
public abstract class Command {

    private final String id;

    protected Command() {
        this.id = UUID.randomUUID().toString();
    }
}
